### ISSUE TITLE
Feedback on Preamble and Chapter 1 - RISC-V N-Trace (Nexus-based Trace) Specification

### ISSUE THREAD

**Issue by ved-rivos** [riscv-non-isa/tg-nexus-trace#30]
1. Specification state should be Stable till AR completes and specification is Freeze approved.
2. Copyright and license - please update to follow the template.
3. "specification for complete end-to-end trace system" may be misleading of the specification as this  spec provides the trace contents.
4. Introduction can be made better and reworded to be a better introduction to the core of the specification.
5. The statement "will be followed by Nexus compliant data.." - not sure its needed here but it should be non-normative -  it "may" be followed by data trace, etc"
6. The para on trace control layer and connectors should move into the corresponding specifications.
7. Reword the informative note e.g. "besides PDF files provided below". Usually donations are to a TG and specifications provided by TG are RVI specifications.
8. Section 1.2 - abruptly starts with a diagram - without enough introduction on what the specification is about.
9. Fig 1 - It is possible that the Encoder and Control Layer will reside within the hart.  It would probably be hard to include both options in a diagram, but a non-normative statement clarifying that the diagram is one possible implementation option would be helpful.
10. Table 1 - Field - "may span across multiple bytes" -> "may span multiple bytes". Punctuation need to be fixed in various places in the table.
11. Table 1 - Variable-length Field - "When messages are transferred" -> "When messages are transmitted" to consistently match terminology used in the last sentence of this description.

**Comment by mipsrobert** [comment]
I am closing all N-Trace PDF related issues with same comments as all issues were handled via comments/discussions in SINGLE Google Docs. Relevant links are as follows:

Notes to N-Trace PDF:   https://docs.google.com/document/d/1h__c0Kc7TQAWMh5bw9cNC9bl_IGqyY_ylPV14uc2xj0

N-Trace PDF rc20:       https://github.com/riscv-non-isa/tg-nexus-trace/commit/221f6b1cef94c5f503554e0cb0deb4046dd49686
N-Trace for ARC review: https://github.com/riscv-non-isa/tg-nexus-trace/commit/1de77dcff1a75197232f72b8fe6863892da0cc74
