### ISSUE TITLE
Feedback on RISC-V Trace Control Interface Specification - Chapter 10 through 14

### ISSUE THREAD

**Issue by ved-rivos** [riscv-non-isa/tg-nexus-trace#38]
1. trAtbBridgeAsyncFreq - explain alignment synchronization packets.
   Explain "maybe the only choice for ..."
2. The chapter 11 does not add much to this specification. It 
   is repeating what are mandatory fields. The fact that a encoder
   and sink are needed is obvious. This chapter can be removed.
3. Chapter 12 is repetition of what has been discussed for the
   various field and does not add more value. This chapter can be
   removed.
4. Chapter 13 is similarly not adding much value. The only guideline
   that may be useful is to disable trace starting at the source - a
   couple of sentences in introduction suffices for this. This chapter
   can be removed.
5. The chapter 11, 12, and 13 may be then replaced with a single 
    guidelines chapter, if needed, that provides precise guidelines
    that are not obvious from previous chapters.
6. Remove chapter 14. Add a note to trTeVerMajor that encoding of
   0 is reserved by this specification. Additional history is not
   requireed. Add a note in the the contributors to acknowleged
   SiFive contribution - the links to that should be removed.

**Comment by mipsrobert** [comment]
All notes to Control PDF handled in 1.0.0_rc20.
