### ISSUE TITLE
PIB, RAM, and ATB alignment synchronization

### ISSUE THREAD

**Issue by ved-rivos** [riscv-non-isa/tg-nexus-trace#56]
PIB, RAM, and ATB have a control field defined to enable generation of alignment synchronization packets. However, these components do not have a trace format (E-trace or N-trace) configuration. As the alignment synchronization sequence is protocol specific, should there should be equivalent of trTeFormat control provided for these components.

**Comment by mipsrobert** [comment]
Closing with the following comment:

NOT DONE: It was not a intention to mix and match different trace protocols, but provide control spec to be identical/re-used by both - at least not now. Such things can be added as future revision/addition (if needed). ARC was against specifying future things, so why do it here. As interfaces between trace components are not defined (by this spec …), nothing prevents ‘trTeFormat’ to be passed from encoder to funnel and sinks.

**Comment by ved-rivos** [comment]
What is the motivation for making trTeFormat as WARL and not RO?
