### ISSUE TITLE
Can SRAM and SMEM sink be regarded as ETF and ETR in coresight, respectively?

### ISSUE THREAD

**Issue by zhangdujiao** [riscv-non-isa/tg-nexus-trace#60]

**Comment by mipsrobert** [comment]
In general we want to avoid using Arm terms directly in the spec😃.

Not exactly. SMEM is ETR what means routing (R) trace to system bus. SRAM is more like ETB. ETF can be a module which supports both SRAM and SMEM modes. Internal SRAM may be used as a destination (if working in SRAM) mode, but it can be used as a FIFO (EFT) in SMEM mode.

**Comment by zhangdujiao** [comment]
thanks! got it
