### ISSUE TITLE
encoder file is missing

### ISSUE THREAD

**Issue by TinuTitus101** [riscv-non-isa/tg-nexus-trace#62]
in trace encoder reference code it is showing that trace messages are read from fNex file but that file is missing . 
If you help to find that file it will help me to develop a trace encoder

**Comment by mipsrobert** [comment]
this 'fNex' file is just a name of variable in C code. Name of file is provided by command line parameter.
For example here: https://github.com/riscv-non-isa/tg-nexus-trace/blob/main/refcode/c/NexRv.c#L219 
In documentation it is sometimes called NEXBIN and -NEX.bin
