### ISSUE TITLE
Should read pointer be used for SMEM mode

### ISSUE THREAD

**Issue by zhangdujiao** [riscv-non-isa/tg-nexus-trace#67]
If the SMEM mode only realize trace data wirte by system BUS, and without additional RAM attached.
Should trRamRPLow and trRamRPHigh registers be realized?

**Comment by mipsrobert** [comment]
This is defined in the spec. Definition of trRamRP says:

Required for SRAM mode and optional for SMEM mode.

and later there is a chapter 'Minimal Trace RAM Sink Register/Fields' which is mentioning trRamRP only in SRAM mode and NOT in SMEM mode.

**Comment by mipsrobert** [comment]
I am closing this issue as there is already enough explanations in the spec.
